
CXX      = g++
CXXFLAGS = -std=c++17 -Iinclude


TARGET = main.exe


SRCS = $(wildcard src/*.cpp)


all: $(TARGET)

$(TARGET): $(SRCS)
	$(CXX) $(CXXFLAGS) $(SRCS) -o $(TARGET)


clean:
	-@del /Q $(TARGET) 2>nul || rm -f $(TARGET)


.PHONY: all clean
